---

# For default configs check out following link
# https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4

#-----------------------------------------------------------
# Layout
#-----------------------------------------------------------

Layout/LineLength:
  Max: 120

#-----------------------------------------------------------
# Lint
#-----------------------------------------------------------

# specs sometimes have useless assignments, which is fine
Lint/UselessAssignment:
  Exclude:
    - 'spec/**/*'

# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: false

#-----------------------------------------------------------
# Metrics
#-----------------------------------------------------------

Metrics/AbcSize:
  Max: 30 # default is 15

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 320

Metrics/CyclomaticComplexity:
  Max: 10 # default is 6

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 10 # default is 7

Metrics/MethodLength:
  Max: 20 # default is 10

#-----------------------------------------------------------
# Style
#-----------------------------------------------------------

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

# kind_of? is a good way to check a type
Style/ClassCheck:
  EnforcedStyle: kind_of?

# We want to allow class Fastlane::Class
Style/ClassAndModuleChildren:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

# The %w might be confusing for new users
Style/WordArray:
  MinSize: 19

# raise and fail are both okay
Style/SignalException:
  Enabled: false

# Better too much 'return' than one missing
Style/RedundantReturn:
  Enabled: false

# Having if in the same line might not always be good
Style/IfUnlessModifier:
  Enabled: false

# Sometimes it's easier to read without guards
Style/GuardClause:
  Enabled: false

# something = if something_else
# that's confusing
Style/ConditionalAssignment:
  Enabled: false

# Better to have too much self than missing a self
Style/RedundantSelf:
  Enabled: false

# We're not there yet
Style/Documentation:
  Enabled: false

# Adds complexity
Style/IfInsideElse:
  Enabled: false
