# frozen_string_literal: true

lib = File.expand_path('lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'simplecov_json/gem_version'

Gem::Specification.new do |spec|
  spec.name          = 'danger-simplecov_json'
  spec.version       = SimpleCovJson::VERSION
  spec.authors       = ['Marcelo Fabri']
  spec.email         = ['marcelofabrimf@gmail.com']
  spec.description   = 'Report your Ruby app test suite code coverage with Danger.'
  spec.summary       = 'A Danger plugin to report code coverage generated by SimpleCov in JSON format.'
  spec.homepage      = 'https://github.com/marcelofabri/danger-simplecov_json'
  spec.license       = 'MIT'

  spec.files         = `git ls-files`.split($INPUT_RECORD_SEPARATOR)
  spec.executables   = spec.files.grep(%r{^bin/}) { |f| File.basename(f) }
  spec.test_files    = spec.files.grep(%r{^(test|spec|features)/})
  spec.require_paths = ['lib']

  spec.required_ruby_version = '>= 2.4.0'

  spec.add_runtime_dependency 'danger-plugin-api', '~> 1.0'

  # General ruby development
  spec.add_development_dependency 'bundler', '>= 1.3'
  spec.add_development_dependency 'rake', '>= 13.0'

  # Testing support
  spec.add_development_dependency 'rspec', '~> 3.4'

  # Linting code and docs
  spec.add_development_dependency 'rubocop', '0.91.1'
  spec.add_development_dependency 'yard', '~> 0.8'

  # Makes testing easy via `bundle exec guard`
  spec.add_development_dependency 'guard', '~> 2.14'
  spec.add_development_dependency 'guard-rspec', '~> 4.7'

  # If you want to work on older builds of ruby
  spec.add_development_dependency 'listen', '3.0.7'

  # This gives you the chance to run a REPL inside your test
  # via
  #    require 'pry'
  #    binding.pry
  # This will stop test execution and let you inspect the results
  spec.add_development_dependency 'pry'
end
